version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      
      - run:
          name: "Check aws version"
          command: |
            aws --version
      
      - run:
          name: "Create CloudFormation Stack"
          command: |
            aws cloudformation deploy \
            --template-file file://network.yml \
            --parameters file://network-param.json \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
  
workflows:
  my_workflow:
    jobs:
      - create-infrastructure
